version: '3.8'

services:
  api:
    image: ghcr.io/haiderbassem/shiftmaster-py:latest
    container_name: shiftmaster_api
    ports:
      - "9292:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    container_name: shiftmaster_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-haidercpp}
      - POSTGRES_DB=${DB_NAME:-shiftmaster_dbsm}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-shiftmaster_dbsm}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
