apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: shiftmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ghcr.io/haiderbassem/shiftmaster-py-auth:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: "prod-db"
        - name: REDIS_URL
          value: "redis://prod-redis:6379/0"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@prod-rabbitmq:5672/"
        - name: DB_PASSWORD
          value: "supersecretpassword"
        - name: DB_USER
          value: "shift_py"
        - name: DB_NAME
          value: "shift_master_py_db"
        - name: JWT_SECRET
          value: "supersecretjwtkeythatislongenough32chars"
        - name: AUTH_SERVICE_URL
          value: "http://prod-auth:8000"
        - name: SCHEDULE_SERVICE_URL
          value: "http://prod-schedule:8000"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://prod-notifications:8000"
        - name: MONOLITH_URL
          value: "http://prod-monolith:8000"
        ports:
        - containerPort: 8000
